name: Development CI

on:
  push:
    branches:
      - main
      - tests
  pull_request:
  workflow_dispatch:

env:
  DB_HOST: postgres
  DB_PORT: 5432
  DB_NAME: devdb
  DB_USER: dev_user
  DB_PASSWORD: dev_fleet_123
  DB_NETWORK: dev_network
  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/openFleetPilot:latest

jobs:
  setup-env:
    name: SetUp Environment
    runs-on: ubuntu-22.04
    outputs:
      db_ready: ${{ steps.wait_for_postgres.outputs.db_ready }}
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_DB: ${{ env.DB_NAME }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - name: Install Postgres client
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Wait for DB to be healthy
        id: wait_for_postgres
        run: |
          for i in {1..20}; do
            if pg_isready -h postgres -p 5432 -U $DB_USER; then
              echo "db_ready=true" >> $GITHUB_OUTPUT
              exit 0
            fi
            echo "Waiting for PostgreSQL..."
            sleep 5
          done
          echo "db_ready=false" >> $GITHUB_OUTPUT
          exit 1

      # - name: Compose build
      #   run: docker compose build
      
      # - name: Compose Up
      #   run: docker compose up -d
  
  build:
    name: Build Software
    runs-on: ubuntu-22.04
    needs: setup-env

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # - name: Use the Docker Container from the releases
      - name: Pull pre-built Image
        run: docker pull ${{ env.DOCKER_IMAGE }}

        # - name: Install Dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libpqxx-dev cmake g++
      
      - name: Build with CMake (Inside Container)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            -e DB_HOST=${{ env.DB_HOST }} \
            -e DB_PORT=${{ env.DB_PORT }} \
            -e DB_NAME=${{ env.DB_NAME }} \
            -e DB_USER=${{ env.DB_USER }} \
            -e DB_PASSWORD=${{ env.DB_PASSWORD }} \
            ${{ env.DOCKER_IMAGE }} \
            bash -c "mkdir -p build && cd build && cmake .. && make"
      
      - name: Archive Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fms_build
          path: build/fms
  
  lint:
    name: code style check
    runs-on: ubuntu-22.04
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Clang-Format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format check
        run: |
          find src include -name "*.cpp" -o -name "*.hpp" | xargs clang-format --dry-run -Werror

  test:
    name: Run DB Connection Test
    runs-on: ubuntu-22.04
    needs: [setup-env, build]

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: fms_build
          path: ./build
      
      - name: Run DB Connection Artifacts
        env:
          DB_HOST: ${{ env.DB_HOST }}
          DB_PORT: ${{ env.DB_PORT }}
          DB_NAME: ${{ env.DB_NAME }}
          DB_USER: ${{ env.DB_USER }}
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_NETWORK: ${{ env.DB_NETWORK }}
        run: |
          ./build/fms